### ISSUE TITLE
Python versions and requirements?

### ISSUE THREAD

**Issue by ddomingof** [NIPS-BRITS/BRITS#1]
Hi, we would like to rerun the scripts and we are not able to run it with python2. 
Which exact requirements and dependencies do we need to install and in which versions?

Thanks

**Comment by HeZhang1994** [comment]
> Hi, we would like to rerun the scripts and we are not able to run it with python2.
> Which exact requirements and dependencies do we need to install and in which versions?
> 
> Thanks

Hi, I have tried this code using python 2.7 and it works. Currently, it seems there is no specific requirement of the version of dependencies for running this code.
